CREATE TABLE SACH(
	Id int NOT NULL PRIMARY KEY  ,--KHOA CHINH
    ten_sach varchar(255),
	Id_tac_gia int ,
    Gio_thieu text,
    doc_thu varchar(255),
    Id_loai_sach int ,
    Id_NSX int ,
    so_trang int,
    ngay_SX varchar(255),
    kich_thuoc varchar(255),
    sku varchar(255),
    trong_luong int,
   	trang_thai tinyint,
    hinh varchar(255),
    don_gia int,
    gia_bia int,
    noi_bat tinyint
    CONSTRAINT FK_SACH_TAC_GIA
   FOREIGN KEY (Id_tac_gia) REFERENCES  TAC_GIA(ID)
   CONSTRAINT FK_SACH_NXB
   FOREIGN KEY(Id_NSX) REFERENCES NXB(ID)

) 
CREATE TABLE LOAI_SACH(
    ID INT NOT NULL CONSTRAINT PK_LOAI_SACH PRIMARY KEY ,--KHOA CHINH
    TEN_LOAI_SACH VARCHAR(255),
    ID_CHA VARCHAR(255),
    TRANG_THAI TINYINT
    CONSTRAINT FK_LOAI_SACH_SACH
    FOREIGN KEY (ID) REFERENCES SACH(Id_loai_sach)
)
CREATE TABLE CHI_TIET_HOA_DON(
    ID INT NOT NULL CONSTRAINT PK_CHI_TIET_HOA_DON PRIMARY KEY,--KHOA CHINH
    ID_DON_HANG INT,
    ID_SACH VARCHAR(255),
    SO_LUONG VARCHAR(255),
    DON_GIA VARCHAR(255),
    THANH_TIEN VARCHAR(255)
    CONSTRAINT FK_CHI_TIET_HOA_DON_SACH
    FOREIGN KEY (ID_SACH) REFERENCES SACH(ID)
     CONSTRAINT FK_CHI_TIET_HOA_DON_DON_HANG
    FOREIGN KEY (ID_DON_HANG) REFERENCES DON_HANG(ID)
)

CREATE TABLE TAC_GIA(
    ID INT NOT NULL CONSTRAINT PK_TAC_GIA PRIMARY KEY,--KHOA CHINH
    TAC_GIA VARCHAR(255),
    NGAY_SINH DATETIME ,
    GIOI_THIEU TEXT 
)
CREATE TABLE NXB(
    ID INT NOT NULL CONSTRAINT PK_NXB PRIMARY KEY,--KHOA CHINH
    TEN_NXB VARCHAR(255),
    DIA_CHI VARCHAR(255),
    DIEN_THOAI VARCHAR(255),
    EMAIL VARCHAR(255)
)

CREATE TABLE SLIDE_BANER(
    ID INT NOT NULL CONSTRAINT PK_SLIDE_BANER PRIMARY KEY ,--KHOA CHINH
    TEN_SLIDE VARCHAR(255),
    HINH VARCHAR(255),
    TRANG_THAI VARCHAR(255),
)

CREATE TABLE TIN_TUC(
    ID INT NOT NULL CONSTRAINT PK_TIN_TUC PRIMARY KEY, --KHOA CHINH
    TIEU_DE_TIN VARCHAR(255),
    NOI_DUNG_TOM_TAT TEXT ,
    NOI_DUNG_CHI_TIET TEXT ,
    TRANG_THAI TINYINT,
    HINH_DAI_DIEN VARCHAR(255),
    ID_LOAI_TIN_TUC INT,
    NGAY_DANG DATETIME 
)

CREATE TABLE DON_HANG(
    ID INT NOT NULL CONSTRAINT PK_DON_HANG PRIMARY KEY,--KHOA CHINH
    MA_DON_HANG VARCHAR(255),
    TONG_TIEN INT,
    NGAY_DAT DATETIME ,
    ID_NGUOI_DUNG VARCHAR(255),
    HO_TEN_NGUOI_NHAN VARCHAR (255),
    EMAIL_NGUOI_NHAN VARCHAR (255),
    SO_DT_NGUOI_NHAN VARCHAR(255),
    TRANG_THAI TINYINT,
    DIA_CHI_NGUOI_NHAN VARCHAR(255)
    CONSTRAINT FK_NGUOIDUNG_DONHANG 
    FOREIGN KEY (ID_NGUOI_DUNG) REFERENCES NGUOI_DUNG(ID) 
)
CREATE TABLE LOAI_NGUOI_DUNG(
    ID INT CONSTRAINT PK_LOAI_NGUOI_DUNG PRIMARY KEY NOT NULL,--KHOA CHINH
    TEN_LOAI_NGUOI_DUNG VARCHAR(255)
    
)

CREATE TABLE LOAI_TIN_TUC(
    ID INT NOT NULL CONSTRAINT PK_LOAI_TIN_TUC PRIMARY KEY,--KHOA CHINH
    TEN_LOAI_TIN VARCHAR(255),
    ALIAS VARCHAR(255),

)
CREATE TABLE NGUOI_DUNG(
    ID INT NOT NULL CONSTRAINT PK_NGUOI_DUNG PRIMARY KEY,--KHOA CHINH
    TAI_KHOAN VARCHAR(255),
    MAT_KHAU VARCHAR(255),
    ID_LOAI_USER INT,
    ID_PHAN_QUYEN INT,
    HO_TEN VARCHAR(255),
    EMAIL VARCHAR(255),
    NGAY_SINH VARCHAR(255),
    DIA_CHI VARCHAR(255),
    DIA_CHI VARCHAR(255),
    DIEM_TICH_LUY INT,
    NGAY_DANG_KY DATETIME ,
    THOI_GIAN_DANG_NHAP DATETIME ,
    ACTIVE_CODE VARCHAR (255),
    SO_LAN_RESERT INT,
    DIEN_THOAI VARCHAR (255)
    CONSTRAINT FK_LOAI_NGUOI_DUNG_NGUOI_DUNG
    FOREIGN KEY (ID_LOAI_USER) REFERENCES LOAI_NGUOI_DUNG(ID)
)

