CREATE TABLE SACH(
	Id int NOT NULL,
    ten_sach varchar(255),
	Id_tac_gia int ,
    Gio_thieu text,
    doc_thu varchar(255),
    Id_loai_sach int NOT NULL,
    Id_NSX int NOT NULL,
    so_trang int,
    ngay_SX varchar(255),
    kich_thuoc varchar(255),
    sku varchar(255),
    trong_luong int,
   	trang_thai tinyint,
    hinh varchar(255),
    don_gia int,
    gia_bia int,
    noi_bat tinyint
)
CREATE TABLE LOAI_SACH(
    ID INT NOT NULL PRIMARY KEY ,
    TEN_LOAI_SACH VARCHAR(255),
    ID_CHA VARCHAR(255),
    TRANG_THAI TINYINT
)
CREATE TABLE CHI_TIET_HOA_DONB(
    ID INT NOT NULL PRIMARY KEY,
    ID_DON_HANG INT,
    ID_SACH VARCHAR(255),
    SO_LUONG VARCHAR(255),
    DON_GIA VARCHAR(255),
    THANH_TIEN VARCHAR(255)

)

CREATE TABLE TAC_GIA(
    ID INT,
    TAC_GIA VARCHAR(255),
    NGAY_SINH DATETIME ,
    GIOI_THIEU TEXT 
)
CREATE TABLE NXB(
    ID INT NOT NULL,
    TEN_NXB VARCHAR(255),
    DIA_CHI VARCHAR(255),
    DIEN_THOAI VARCHAR(255),
    EMAIL VARCHAR(255)
)

CREATE TABLE SLIDE_BANER(
    ID INT NOT NULL ,
    TEN_SLIDE VARCHAR(255),
    HINH VARCHAR(255),
    TRANG_THAI VARCHAR(255),
)

CREATE TABLE TIN_TUC(
    ID INT NOT NULL,
    TIEU_DE_TIN VARCHAR(255),
    NOI_DUNG_TOM_TAT TEXT ,
    NOI_DUNG_CHI_TIET TEXT ,
    TRANG_THAI TINYINT,
    HINH_DAI_DIEN VARCHAR(255),
    ID_LOAI_TIN_TUC INT,
    NGAY_DANG DATETIME 
)

CREATE TABLE DON_HANG(
    ID INT NOT NULL,
    MA_DON_HANG VARCHAR(255),
    TONG_TIEN INT,
    NGAY_DAT DATETIME ,
    ID_NGUOI_DUNG VARCHAR(255),
    HO_TEN_NGUOI_NHAN VARCHAR (255),
    EMAIL_NGUOI_NHAN VARCHAR (255),
    SO_DT_NGUOI_NHAN VARCHAR(255),
    TRANG_THAI TINYINT,
    DIA_CHI_NGUOI_NHAN VARCHAR(255)
)
CREATE TABLE LOAI_NGUOI_DUNG(
    ID INT NOT NULL,
    TEN_LOAI_NGUOI_DUNG VARCHAR(255)

)

CREATE TABLE LOAI_TIN_TUC(
    ID INT NOT NULL,
    TEN_LOAI_TIN VARCHAR(255),
    ALIAS VARCHAR(255),

)
CREATE TABLE NGUOI_DUNG(
    ID INT NOT NULL,
    TAI_KHOAN VARCHAR(255),
    MAT_KHAU VARCHAR(255),
    ID_LOAI_USER INT,
    ID_PHAN_QUYEN INT,
    HO_TEN VARCHAR(255),
    EMAIL VARCHAR(255),
    NGAY_SINH VARCHAR(255),
    DIA_CHI VARCHAR(255),
    DIA_CHI VARCHAR(255),
    DIEM_TICH_LUY INT,
    NGAY_DANG_KY DATETIME ,
    THOI_GIAN_DANG_NHAP DATETIME ,
    ACTIVE_CODE VARCHAR (255),
    SO_LAN_RESERT INT,
    DIEN_THOAI VARCHAR (255)
)

USE book_store